version: '2'

services:

  dev:
    build: .
    image: keboola/sliced-files-packer
    mem_limit: 128m
    tty: true
    stdin_open: true
    command: >-
             sh -c '
             composer install
             && composer run-script tests
             '
    volumes:
      - ./:/code
    environment:
      KBC_COMPONENTID: keboola.sliced-files-downloader

  tests-ci:
    image: keboola/sliced-files-packer
    command: >-
             sh -c '
             composer run-script tests
             '
    environment:
      KBC_COMPONENTID: keboola.sliced-files-downloader
